---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: whoami
  namespace: whoami
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: whoami-webhook-receiver-token
  resources:
    - kind: GitRepository
      name: whoami
